### ISSUE TITLE
can't see pinia and routes tab

### ISSUE THREAD

**Issue by ndriodna** [hzmming/vue-force-dev#14]
### Production
![image](https://github.com/hzmming/vue-force-dev/assets/27008469/a7d04c02-02f3-4ebb-9745-7ad4d8ff8ac2)
<hr/>

### Local
![image](https://github.com/hzmming/vue-force-dev/assets/27008469/1875829e-ad73-4172-bb3a-20d176d1510a)

**Comment by kissu** [comment]
Indeed, it's fine [with routes and Vuex](https://vueschool.io/plans) but struggles to find Pinia apparently (maybe it's too new for the extension or maybe more tricky to fetch)? Still, there is probably a way to access it through the components without too much struggle.

**Comment by ultimateshadsform** [comment]
The reason is because on production the _p thing is empty.

![image](https://github.com/hzmming/vue-force-dev/assets/151234273/3ad21ec4-acc4-4cda-adb6-2196f0f4dfed)

But on a dev website it is filled:

![image](https://github.com/hzmming/vue-force-dev/assets/151234273/35560bed-7045-4f91-8217-2b77db58bd97)


Might be a lead.

**Comment by hzmming** [comment]
The latest 2.0.0 version already supports Pinia.

I don't think the Vue Router is that important, and I need to spend some time researching it. I don't plan to support it at the moment. 
If you agree, you can close the issue, otherwise you can say more about your opinion, thanks.
